spring:
  application:
    name: ms-ventas-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
